# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    #obj = bld.create_ns3_program('aggregator-example', ['aggregator'])
    #obj.source = 'aggregator-example.cc'

