# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('aggregator', ['core', 'applications', 'wifi', 'network', 'stats', 'internet', 'batmand', 'olsr'])
    module.source = [
        'model/aggregator.cc',
        'helper/aggregator-helper.cc',
        ]

    #module_test = bld.create_ns3_module_test_library('aggregator')
    #module_test.source = [
    #    'test/aggregator-test-suite.cc',
    #    ]

    headers = bld(features='ns3header')
    headers.module = 'aggregator'
    headers.source = [
        'model/aggregator.h',
        'helper/aggregator-helper.h',
        ]

    #if bld.env.ENABLE_EXAMPLES:
    #    bld.recurse('examples')

    # bld.ns3_python_bindings()

